#!/usr/bin/env python3
"""Render the workshop's Mermaid sources to SVG.

WHY THIS EXISTS. `content/modules/ROOT/examples/diagrams/**/*.mmd` holds the extracted diagram
sources, and the per-module `media-manifest.md` files ask for ~90 SVG exports of them. None
existed. The decks DO carry rendered diagrams (commit 3534801, "81 rendered diagrams"), but
neither the renderer nor its intermediate files were committed — so those diagrams could not
be regenerated by anyone, and a source edit could not reach them. This script closes that.

HOW. Mermaid is a browser library, so rendering means running it in a browser. Playwright is
already a dependency of the capture harness, and mermaid is loaded from a CDN, so this adds no
new install. Each .mmd is rendered in an isolated page and its SVG written out.

OUTPUT. content/modules/ROOT/assets/images/<slug>/<slug>-<NN>-<name>.svg — the filename the
manifests expect, derived from the source path (<slug>/<NN>-<name>.mmd).

USAGE
    python render_diagrams.py [--only <slug>] [--dry-run]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from playwright.sync_api import Error as PlaywrightError
from playwright.sync_api import sync_playwright

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "content" / "modules" / "ROOT" / "examples" / "diagrams"
OUT_ROOT = REPO_ROOT / "content" / "modules" / "ROOT" / "assets" / "images"

# Rendered at a generous width so text stays crisp when the SVG is scaled down in a lab page or
# blown up on a slide. `htmlLabels: false` keeps labels as SVG <text>, which survives being
# embedded in PowerPoint — HTML labels rely on foreignObject and render blank there.
PAGE = """<!doctype html>
<html><head><meta charset="utf-8"><style>body{margin:0;background:#fff}</style></head>
<body><div id="out"></div>
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
  mermaid.initialize({
    startOnLoad: false,
    theme: 'neutral',
    // htmlLabels must be set at the TOP level as well as per-diagram: setting it only under
    // `flowchart` left every node label as a <foreignObject> (measured — 9 of them in one
    // diagram). Browsers render those fine, but PowerPoint does not, and the manifests reuse
    // these diagrams on slides.
    htmlLabels: false,
    flowchart: {htmlLabels: false, useMaxWidth: false},
    sequence: {useMaxWidth: false},
    er: {useMaxWidth: false},
  });
  window.renderMermaid = async (src) => {
    const {svg} = await mermaid.render('d' + Math.floor(performance.now()), src);
    return svg;
  };
  window.mermaidReady = true;
</script></body></html>"""


def out_path_for(src: Path) -> Path:
    """content/.../examples/diagrams/<slug>/<NN>-<name>.mmd -> assets/images/<slug>/<slug>-<NN>-<name>.svg"""
    slug = src.parent.name
    return OUT_ROOT / slug / f"{slug}-{src.stem}.svg"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", help="render just this module slug")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    sources = sorted(SRC_ROOT.rglob("*.mmd"))
    if args.only:
        sources = [s for s in sources if s.parent.name == args.only]
    if not sources:
        sys.exit(f"no .mmd sources under {SRC_ROOT}")

    print(f"{len(sources)} source(s)")
    if args.dry_run:
        for s in sources[:10]:
            print(f"  {s.relative_to(REPO_ROOT)} -> {out_path_for(s).relative_to(REPO_ROOT)}")
        if len(sources) > 10:
            print(f"  … and {len(sources) - 10} more")
        return 0

    ok, failed = 0, []
    with sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome", headless=True)
        page = browser.new_page()
        page.set_content(PAGE)
        try:
            page.wait_for_function("() => window.mermaidReady === true", timeout=60_000)
        except PlaywrightError:
            sys.exit("mermaid did not load from the CDN — check network access")

        for src in sources:
            text = src.read_text()
            try:
                svg = page.evaluate("(s) => window.renderMermaid(s)", text)
            except PlaywrightError as exc:
                # A syntax error in one diagram must not abort the batch, and it IS a finding:
                # the source is what the lab pages render too.
                failed.append((src, str(exc).splitlines()[0][:120]))
                continue
            dest = out_path_for(src)
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(svg)
            ok += 1

        browser.close()

    print(f"\nrendered {ok}/{len(sources)}")
    for src, err in failed:
        print(f"  FAILED {src.relative_to(REPO_ROOT)}: {err}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
