#!/usr/bin/env python3
"""Render the workshop's Mermaid sources to SVG.

WHY THIS EXISTS. `content/modules/ROOT/examples/diagrams/**/*.mmd` holds the extracted diagram
sources, and the per-module `media-manifest.md` files ask for ~90 SVG exports of them. None
existed. The decks DO carry rendered diagrams (commit 3534801, "81 rendered diagrams"), but
neither the renderer nor its intermediate files were committed — so those diagrams could not
be regenerated by anyone, and a source edit could not reach them. This script closes that.

HOW. Mermaid is a browser library, so rendering means running it in a browser. Playwright is
already a dependency of the capture harness, and mermaid is loaded from a CDN, so this adds no
new install. Each .mmd is rendered in an isolated page and its SVG written out.

OUTPUT. content/modules/ROOT/assets/images/<slug>/<slug>-<NN>-<name>.svg — the filename the
manifests expect, derived from the source path (<slug>/<NN>-<name>.mmd).

USAGE
    python render_diagrams.py [--only <slug>] [--dry-run]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from playwright.sync_api import Error as PlaywrightError
from playwright.sync_api import sync_playwright

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "content" / "modules" / "ROOT" / "examples" / "diagrams"
OUT_ROOT = REPO_ROOT / "content" / "modules" / "ROOT" / "assets" / "images"

# Rendered at a generous width so text stays crisp when the SVG is scaled down in a lab page or
# blown up on a slide. `htmlLabels: false` keeps labels as SVG <text>, which survives being
# embedded in PowerPoint — HTML labels rely on foreignObject and render blank there.
PAGE = """<!doctype html>
<html><head><meta charset="utf-8"><style>body{margin:0;background:#fff}</style></head>
<body><div id="out"></div>
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
  mermaid.initialize({
    startOnLoad: false,
    theme: 'neutral',
    // htmlLabels must be set at the TOP level as well as per-diagram: setting it only under
    // `flowchart` left every node label as a <foreignObject> (measured — 9 of them in one
    // diagram). Browsers render those fine, but PowerPoint does not, and the manifests reuse
    // these diagrams on slides.
    htmlLabels: false,
    flowchart: {htmlLabels: false, useMaxWidth: false},
    sequence: {useMaxWidth: false},
    er: {useMaxWidth: false},
  });
  window.renderMermaid = async (src) => {
    const {svg} = await mermaid.render('d' + Math.floor(performance.now()), src);
    return svg;
  };
  window.mermaidReady = true;
</script></body></html>"""


def out_path_for(src: Path) -> Path:
    """content/.../examples/diagrams/<slug>/<NN>-<name>.mmd -> assets/images/<slug>/<slug>-<NN>-<name>.svg"""
    slug = src.parent.name
    return OUT_ROOT / slug / f"{slug}-{src.stem}.svg"


# The price of `htmlLabels: false`, and it is invisible unless you LOOK at a render.
#
# With HTML labels off, mermaid emits each word of a label as its own <tspan>, carrying the
# separating space as a LEADING space on the next one:
#
#     <tspan>on</tspan><tspan> repeated</tspan><tspan> failure</tspan>
#
# SVG's default xml:space strips leading and trailing whitespace per text chunk, so every one
# of those spaces disappears and the label renders "onrepeatedfailure". It afflicted all 81
# committed diagrams ("every5min", "you:POSTaCloudEvent", "dead-lettersink") and nothing caught
# it, because mermaid raises no error, the SVG is well-formed, and the byte count looks healthy.
#
# xml:space="preserve" on the <text> element restores them. It is safe here specifically because
# mermaid emits no formatting whitespace between the tags — there is nothing else to preserve.
#
# Note the live lab pages are NOT affected: the Antora sites set `html_labels: true`, so their
# labels are foreignObject HTML. This is an export-path-only defect — which is exactly why it
# survived: the surface everyone looks at is the one that was fine.
_TEXT_OPEN = re.compile(r"<text(?![\w-])")


def preserve_label_spaces(svg: str) -> str:
    return _TEXT_OPEN.sub('<text xml:space="preserve"', svg)


def spacing_is_broken(svg: str) -> bool:
    """True if any <text> still lacks xml:space — the regression guard for the above."""
    return any(not m.endswith('xml:space="preserve"') for m in re.findall(r"<text(?:\s+xml:space=\"preserve\")?", svg))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", help="render just this module slug")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    sources = sorted(SRC_ROOT.rglob("*.mmd"))
    if args.only:
        sources = [s for s in sources if s.parent.name == args.only]
    if not sources:
        sys.exit(f"no .mmd sources under {SRC_ROOT}")

    print(f"{len(sources)} source(s)")
    if args.dry_run:
        for s in sources[:10]:
            print(f"  {s.relative_to(REPO_ROOT)} -> {out_path_for(s).relative_to(REPO_ROOT)}")
        if len(sources) > 10:
            print(f"  … and {len(sources) - 10} more")
        return 0

    ok, failed = 0, []
    with sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome", headless=True)
        page = browser.new_page()
        page.set_content(PAGE)
        try:
            page.wait_for_function("() => window.mermaidReady === true", timeout=60_000)
        except PlaywrightError:
            sys.exit("mermaid did not load from the CDN — check network access")

        for src in sources:
            text = src.read_text()
            try:
                svg = page.evaluate("(s) => window.renderMermaid(s)", text)
            except PlaywrightError as exc:
                # A syntax error in one diagram must not abort the batch, and it IS a finding:
                # the source is what the lab pages render too.
                failed.append((src, str(exc).splitlines()[0][:120]))
                continue
            svg = preserve_label_spaces(svg)
            if spacing_is_broken(svg):
                failed.append((src, "label spaces would be stripped — see preserve_label_spaces()"))
                continue
            dest = out_path_for(src)
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(svg)
            ok += 1

        browser.close()

    print(f"\nrendered {ok}/{len(sources)}")
    for src, err in failed:
        print(f"  FAILED {src.relative_to(REPO_ROOT)}: {err}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
