#!/usr/bin/env python3
"""FIXTURE for _canary-coverage.py — a guard with one detector NO canary can witness.

Not a real guard; see proven-guard.py beside it for the same disclaimer.

This one reproduces a real shape from the audit of 2026-08-01: a pattern that ENABLES detection
rather than triggering it. `UNUSED_RE` skips lines it matches, and neither the real run nor the
canary contains a line it matches — so blinding it (making it match nothing) removes a skip that
never fired. Both modes keep their exit codes. That is the curl-format `INTRINSIC_ATTRIBUTES`
shape and the click-to-run `_LEADING_LOOP_RE` shape: blinding makes the guard QUIETER (or, here,
changes nothing at all), so no safe case can ever witness it, and every case that touched it was a
safe case — which is precisely why it looked covered.

The gate must classify:
  emit:find_offenders:*  PROVEN   — the canary's defect line disappears when it is no-oped.
  pattern:UNUSED_RE      UNPROVEN — nothing moves either exit code.

DO NOT "fix" this fixture by adding a case for UNUSED_RE. Its whole job is to be the negative half
of the gate's self-test. Fixing it makes `_canary-coverage.py --self-test` fail, correctly, with
"classified [] as unproven, expected ['pattern:UNUSED_RE']".
"""

import argparse
import pathlib
import re
import sys
import tempfile

DEFECT = "SHOUTY-DEFECT"


def _compile(name, pattern, flags=0):
    """Same crash-to-2 contract the real guards use; a bad regex must not exit 1."""
    try:
        return re.compile(pattern, flags)
    except re.error as exc:
        print(f"unproven-guard fixture: {name} is not a valid regex ({exc})", file=sys.stderr)
        sys.exit(2)


# The unwitnessable detector. A generated-file banner nothing in either corpus carries.
UNUSED_RE = _compile("UNUSED_RE", r"^// GENERATED BY A ROBOT — DO NOT EDIT$")


def find_offenders(path: pathlib.Path):
    """Yield (line_no, text) for every defect, skipping generated-file banners."""
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if UNUSED_RE.search(line):
            continue
        if DEFECT in line:
            yield (number, line.strip())


def scan(directory: pathlib.Path) -> list:
    return [(path.name, *hit) for path in sorted(directory.glob("*.txt"))
            for hit in find_offenders(path)]


CLEAN = "nothing to see here\nan ordinary line\n"
CANARY = "an ordinary line\nthis line carries SHOUTY-DEFECT\n"


def _materialise(directory: pathlib.Path, text: str) -> None:
    (directory / "sample.txt").write_text(text, encoding="utf-8")


def check() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(tmp)
        _materialise(root, CLEAN)
        offenders = scan(root)
    if offenders:
        print(f"unproven-guard fixture: {len(offenders)} offender(s): {offenders}")
        return 1
    print("unproven-guard fixture: clean.")
    return 0


def self_test() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(tmp)
        _materialise(root, CANARY)
        offenders = scan(root)
    lines = sorted(hit[1] for hit in offenders)
    if lines != [2]:
        print(f"unproven-guard fixture SELF-TEST FAILED: expected the defect on line 2; got "
              f"{lines}.", file=sys.stderr)
        return 2
    print("unproven-guard fixture: canary detected on line 2 (rc=1).")
    return 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    rc = self_test() if args.self_test else check()

    if args.self_test:
        # An INLINE self-test assertion. click-to-run, curl-format and version-anchor all keep
        # theirs in main() behind exactly this condition instead of in a self_test() function, and
        # this block is the gate's only witness that it prunes such a branch out of the real-run
        # call graph. Blind `_is_self_test_branch()` and `failures.append(…)` below enumerates as
        # a detector, which nothing can ever witness, and the gate's own --self-test fails on the
        # enumeration count. Do not "tidy" this into self_test() — it is load-bearing there.
        failures = []
        if rc != 1:
            failures.append("the canary scan did not report the one defect it was built around")
        if failures:
            for failure in failures:
                print(f"unproven-guard fixture SELF-TEST FAILED — {failure}", file=sys.stderr)
            return 2
    return rc


if __name__ == "__main__":
    sys.exit(main())
