# Suggested namespace of the Tempo Operator (tempo-product, AllNamespaces install mode).
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-tempo-operator
  labels:
    portfolio.redhat.com/component: tempo
