# Web Terminal operator — global (openshift-operators has the cluster-wide OperatorGroup).
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    # Wave 0 = the controller. Its DevWorkspace operands are created on demand by attendees, not by us.
    argocd.argoproj.io/sync-wave: "0"
  name: web-terminal
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: web-terminal
  source: redhat-operators
  sourceNamespace: openshift-marketplace
