#!/usr/bin/env bash
#
# gen-attributes.sh — generate the AsciiDoc product-version attribute partial from
# versions.yaml (the single source of truth, 01-ARCHITECTURE §6).
#
# Content references product versions ONLY through these attributes (04-STYLE-GUIDE §5):
# a page writes `{gitops_version}`, never the literal "1.21.1". This script emits one
# `:<key>_version:` attribute for every top-level product entry in versions.yaml that
# has a `version:` field (entries without one, e.g. gitea, are skipped).
#
# Idempotent: same versions.yaml -> byte-identical output. CI runs this and then
# `git diff --exit-code` on the output file as a drift gate — if versions.yaml changed
# without regenerating, CI fails.
#
# Usage:  tools/gen-attributes.sh          # regenerate in place
#         tools/gen-attributes.sh --check  # exit 1 if the committed file is stale
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
versions_file="${repo_root}/versions.yaml"
out_file="${repo_root}/content/modules/ROOT/partials/version-attributes.adoc"

if ! command -v yq >/dev/null 2>&1; then
  echo "❌ yq (github.com/mikefarah/yq) not found on PATH — needed to read versions.yaml." >&2
  echo "   Install it or run this in CI where it is provisioned." >&2
  exit 1
fi

if [ ! -f "$versions_file" ]; then
  echo "❌ versions.yaml not found at ${versions_file}." >&2
  exit 1
fi

verified="$(yq eval '.verified // "unknown"' "$versions_file")"

# Build the partial in a temp file, then move into place (atomic, and lets --check diff).
tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

{
  echo "// GENERATED by tools/gen-attributes.sh from versions.yaml — DO NOT EDIT BY HAND."
  echo "// Product versions for content prose (04-STYLE-GUIDE §5). Regenerate after editing"
  echo "// versions.yaml; CI fails if this file drifts from the source of truth."
  echo "// versions.yaml verified: ${verified}"
  echo "//"
  # One `:<key>_version: <value>` per top-level map entry that has a non-null version.
  # `to_entries` preserves document order -> deterministic, idempotent output.
  yq eval \
    'to_entries | .[]
       | select(.value | type == "!!map")
       | select(.value.version != null)
       | ":" + .key + "_version: " + (.value.version | tostring)' \
    "$versions_file"
} > "$tmp_file"

if [ "${1:-}" = "--check" ]; then
  if [ ! -f "$out_file" ] || ! diff -q "$out_file" "$tmp_file" >/dev/null 2>&1; then
    echo "❌ ${out_file#"${repo_root}/"} is stale." >&2
    echo "   Fix: run tools/gen-attributes.sh and commit the result." >&2
    if [ -f "$out_file" ]; then
      diff -u "$out_file" "$tmp_file" >&2 || true
    fi
    exit 1
  fi
  echo "✅ version-attributes.adoc is in sync with versions.yaml (verified ${verified})."
  exit 0
fi

mkdir -p "$(dirname "$out_file")"
mv "$tmp_file" "$out_file"
trap - EXIT
echo "✅ Wrote ${out_file#"${repo_root}/"} ($(grep -c '^:' "$out_file") version attributes, verified ${verified})."
