#!/usr/bin/env bash
#
# gen-module-slugs.sh — materialize the module catalog's SLUGS into a marked, generated
# block in gitops/workshop-config/values.yaml (moduleSlugs:), sourced from modules.yaml
# (the single source of truth for module order/identity, 01-ARCHITECTURE §Entry-state system).
#
# Why this exists (the same shape as versions.yaml -> tools/gen-attributes.sh):
#   The workshop-config chart's per-user Argo RBAC (templates/per-user-argo-rbac.yaml) grants each
#   attendee patch/delete on ONLY their own entry Applications, named entry-<slug>-<user>. Kubernetes
#   RBAC resourceNames cannot wildcard, and Helm cannot read /modules.yaml (it lives OUTSIDE the chart
#   root, so `.Files`/`.Values` can't reach it). So the catalog's slugs are generated INTO the chart's
#   values.yaml here, and the template ranges over .Values.moduleSlugs. Editing modules.yaml is
#   therefore a two-file change: modules.yaml + the regenerated block (exactly like versions.yaml).
#
# Idempotent: same modules.yaml -> byte-identical values.yaml. CI runs `--check` as a drift gate
# (content-build.yml) — if modules.yaml changed without regenerating, CI fails.
#
# Usage:  tools/gen-module-slugs.sh          # rewrite the generated block in place
#         tools/gen-module-slugs.sh --check  # exit 1 if the committed block is stale
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
modules_file="${repo_root}/modules.yaml"
out_file="${repo_root}/gitops/workshop-config/values.yaml"

# Marker lines that fence the generated block inside values.yaml (YAML comments, so the file stays
# valid Helm values whether or not the block has been generated yet).
begin_marker="# BEGIN gen-module-slugs — GENERATED by tools/gen-module-slugs.sh, DO NOT EDIT"
end_marker="# END gen-module-slugs"

if [ ! -f "$modules_file" ]; then
  echo "❌ modules.yaml not found at ${modules_file}." >&2
  exit 1
fi
if [ ! -f "$out_file" ]; then
  echo "❌ ${out_file#"${repo_root}/"} not found — nothing to inject the generated block into." >&2
  exit 1
fi

# Ordered slug list from modules.yaml. yq v4 is the parser, with the dependency-free awk fallback
# lifted verbatim from tools/ws/ws (_module_rows) so this generator runs even on a host without yq —
# match house style. Both paths yield one slug per module in catalog order.
module_slugs() {
  if command -v yq >/dev/null 2>&1; then
    yq -r '.modules[].slug' "$modules_file" 2>/dev/null
  else
    awk '
      /^[[:space:]]*-[[:space:]]*slug:[[:space:]]*/ {
        s=$0; sub(/^.*slug:[[:space:]]*/,"",s); gsub(/["'\''[:space:]]/,"",s); print s }
    ' "$modules_file"
  fi
}

# Render the marked block (markers + moduleSlugs list) to a temp file.
block_file="$(mktemp)"
trap 'rm -f "$block_file" "${new_file:-}"' EXIT
{
  echo "$begin_marker"
  echo "# Regenerate after editing modules.yaml (CI drift gate, like versions.yaml -> gen-attributes.sh)."
  echo "# Consumed by templates/per-user-argo-rbac.yaml to resourceName-scope each attendee's patch/delete"
  echo "# to THEIR OWN entry Applications (entry-<slug>-<user>): k8s RBAC resourceNames can't wildcard and"
  echo "# Helm can't read /modules.yaml (outside the chart root), so the catalog's slugs are generated here."
  echo "moduleSlugs:"
  module_slugs | sed 's/^/  - /'
  echo "$end_marker"
} > "$block_file"

# Sanity: a zero-slug block would silently strip every attendee's entry-app RBAC — fail loud instead.
slug_count="$(grep -c '^  - ' "$block_file" || true)"
if [ "$slug_count" -eq 0 ]; then
  echo "❌ no module slugs parsed from ${modules_file#"${repo_root}/"} — refusing to write an empty moduleSlugs." >&2
  echo "   Check that modules.yaml has 'modules:' entries with a 'slug:' each, or install yq." >&2
  exit 1
fi

# Splice the fresh block into values.yaml: replace an existing marked block in place, or append it at
# EOF the first time (no markers yet). Everything outside the markers is passed through untouched.
new_file="$(mktemp)"
awk -v blockfile="$block_file" -v beginm="$begin_marker" -v endm="$end_marker" '
  BEGIN {
    block=""; while ((getline l < blockfile) > 0) block = block l "\n"; close(blockfile)
    sub(/\n$/, "", block)   # print re-adds the final newline
    found=0
  }
  index($0, beginm) == 1 { inblock=1; found=1; print block; next }  # on BEGIN: emit fresh block once
  index($0, endm)   == 1 { inblock=0; next }                        # swallow the old END marker
  inblock { next }                                                  # swallow old block body
  { print }
  END { if (!found) { print ""; print block } }                    # first run: append at EOF
' "$out_file" > "$new_file"

if [ "${1:-}" = "--check" ]; then
  if ! diff -q "$out_file" "$new_file" >/dev/null 2>&1; then
    echo "❌ ${out_file#"${repo_root}/"} moduleSlugs block is stale (drifted from modules.yaml)." >&2
    echo "   Fix: run tools/gen-module-slugs.sh and commit the result." >&2
    diff -u "$out_file" "$new_file" >&2 || true
    exit 1
  fi
  echo "✅ moduleSlugs in ${out_file#"${repo_root}/"} is in sync with modules.yaml (${slug_count} modules)."
  exit 0
fi

mv "$new_file" "$out_file"
echo "✅ Wrote moduleSlugs block to ${out_file#"${repo_root}/"} (${slug_count} modules, catalog order)."
