#!/usr/bin/env bash
#
# gen-module-stacks.sh — materialize the module catalog's slug->stacks map into a marked,
# generated block in helm/bootstrap/values.yaml (moduleCatalog:), sourced from modules.yaml
# (the single source of truth for module order/identity + per-module stack deps).
#
# Why this exists (same shape as versions.yaml -> gen-attributes.sh and modules.yaml ->
# gen-module-slugs.sh): the helm/bootstrap FSC chart derives the platform-stack set from the
# deployer's `modulesDisabled` list, but Helm CANNOT read /modules.yaml (it lives OUTSIDE the
# chart root, so `.Files`/`.Values` can't reach it). So the ordered catalog — each module's
# slug and the stacks its lab requires — is generated INTO the chart's values.yaml here, and
# the templates range over .Values.moduleCatalog. Editing modules.yaml is therefore a
# multi-file change: modules.yaml + this block + the moduleSlugs block (gen-module-slugs.sh).
#
# The list is ORDERED (position = module number), so the chart resolves an `mNN` token by index
# just as bootstrap/install.sh does.
#
# Idempotent: same modules.yaml -> byte-identical values.yaml. CI runs `--check` as a drift gate.
#
# Usage:  tools/gen-module-stacks.sh          # rewrite the generated block in place
#         tools/gen-module-stacks.sh --check  # exit 1 if the committed block is stale
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
modules_file="${repo_root}/modules.yaml"
out_file="${repo_root}/helm/bootstrap/values.yaml"

# Marker lines that fence the generated block inside values.yaml (YAML comments, so the file stays
# valid Helm values whether or not the block has been generated yet).
begin_marker="# BEGIN gen-module-stacks — GENERATED by tools/gen-module-stacks.sh, DO NOT EDIT"
end_marker="# END gen-module-stacks"

if [ ! -f "$modules_file" ]; then
  echo "❌ modules.yaml not found at ${modules_file}." >&2
  exit 1
fi
if [ ! -f "$out_file" ]; then
  echo "❌ ${out_file#"${repo_root}/"} not found — nothing to inject the generated block into." >&2
  exit 1
fi
# Unlike gen-module-slugs.sh, this generator needs real YAML list handling (the stacks arrays),
# so yq v4 is a hard dependency here — no awk fallback.
if ! command -v yq >/dev/null 2>&1; then
  echo "❌ yq (mikefarah v4) is required by gen-module-stacks.sh — install it (brew install yq)." >&2
  exit 1
fi

# Render the marked block (markers + moduleCatalog list) to a temp file. The catalog BODY is
# emitted straight from yq (ordered {slug, stacks} objects) so the stacks arrays stay real YAML,
# then indented two spaces to nest under `moduleCatalog:`.
block_file="$(mktemp)"
new_file=""
trap 'rm -f "$block_file" "${new_file:-}"' EXIT
{
  echo "$begin_marker"
  echo "# Regenerate after editing modules.yaml (CI drift gate). Consumed by templates/_helpers.tpl"
  echo "# (ogsr-bootstrap.requiredStacks) to derive the platform-stack set from .Values.modulesDisabled:"
  echo "# Helm can't read /modules.yaml, so the ordered slug->stacks catalog is generated here."
  echo "moduleCatalog:"
  yq -o=yaml -I=2 '.modules | map({"slug": .slug, "stacks": (.stacks // [])})' "$modules_file" \
    | sed 's/^/  /'
  echo "$end_marker"
} > "$block_file"

# Sanity: a zero-row block would make EVERY module look stack-free (the whole platform would
# collapse to baseline) — fail loud instead of writing an empty catalog.
row_count="$(grep -c '^  - slug: ' "$block_file" || true)"
if [ "$row_count" -eq 0 ]; then
  echo "❌ no modules parsed from ${modules_file#"${repo_root}/"} — refusing to write an empty moduleCatalog." >&2
  exit 1
fi

# Splice the fresh block into values.yaml: replace an existing marked block in place, or append it
# at EOF the first time (no markers yet). Everything outside the markers passes through untouched.
new_file="$(mktemp)"
awk -v blockfile="$block_file" -v beginm="$begin_marker" -v endm="$end_marker" '
  BEGIN {
    block=""; while ((getline l < blockfile) > 0) block = block l "\n"; close(blockfile)
    sub(/\n$/, "", block)   # print re-adds the final newline
    found=0
  }
  index($0, beginm) == 1 { inblock=1; found=1; print block; next }  # on BEGIN: emit fresh block once
  index($0, endm)   == 1 { inblock=0; next }                        # swallow the old END marker
  inblock { next }                                                  # swallow old block body
  { print }
  END { if (!found) { print ""; print block } }                    # first run: append at EOF
' "$out_file" > "$new_file"

if [ "${1:-}" = "--check" ]; then
  if ! diff -q "$out_file" "$new_file" >/dev/null 2>&1; then
    echo "❌ ${out_file#"${repo_root}/"} moduleCatalog block is stale (drifted from modules.yaml)." >&2
    echo "   Fix: run tools/gen-module-stacks.sh and commit the result." >&2
    diff -u "$out_file" "$new_file" >&2 || true
    exit 1
  fi
  echo "✅ moduleCatalog in ${out_file#"${repo_root}/"} is in sync with modules.yaml (${row_count} modules)."
  exit 0
fi

mv "$new_file" "$out_file"
new_file=""
echo "✅ Wrote moduleCatalog block to ${out_file#"${repo_root}/"} (${row_count} modules, catalog order)."
